### ISSUE TITLE
WITH-OPEN-STREAM may be used incorrectly in call-w/stdin and call-w/stdout

### ISSUE THREAD

**Issue by Yehouda** [g000001/arc-compat#3]
in file ac.lisp,  the functions **arc:call-w/stdin** and **arc:call-w/stdout** both use **with-open-stream**,  which closes the stream on exit. That is probably not the intention. 

It specifically goes wrong when **arc:call-w/stdout** is called to output into a string stream and then getting the string of the stream, because calling **get-output-stream-string** on a closed stream gives "unspecifed results" (see entry for **CLOSE** in the ANSI standard). The test **(tst call-w/stdout  .. )** in test-after.lisp fails because of that on LispWorks. 

If the closing of the stream intentional, then the test needs to be changed such that the call to **get-output-stream-string**  (**arc:inside**, which is fbound to **#'get-output-stream-string**) needs to be inside the **with-open-stream**, so the call happens before the stream is closed.

**Comment by g000001** [comment]
Thank you for your reporting!
fixed! f2c55cc
