### ISSUE TITLE
The tests effectively assume ordering of items in hash-tables

### ISSUE THREAD

**Issue by Yehouda** [g000001/arc-compat#4]
Both the test OBJ in table.lisp and the test DEDUP in list.lisp (last check with the result of calling **obj**) effectively assume specific order of items inside a hash-table, because they generate a list by mapping over a hash table and compare the result to a list with a specific order. That cause these tests to fail unpredictably. 

They may be other tests with the same issue, I didn't check systemetically.

**Comment by g000001** [comment]
Thank you for your reporting!
fixed! aa54a5b
