### ISSUE TITLE
The test for SINCE can fail sometimes.

### ISSUE THREAD

**Issue by Yehouda** [g000001/arc-compat#6]
The current test for **since** currently does;
`(== 1 (let t0 (seconds) (sleep 1) (since t0))`
which may fail if the first **seconds** happens just before the switch  to returning the next second, and the **sleep**
plus the rest of processing takes a little more a second. It fails to me once in several tens runs of the test-suite.
I suggest change it like this: 

```
 (tst since
    (== t (let t0 (seconds) (sleep 0.99)
            (cl:let ((s1 (since t0)))
              (or (cl:= s1 1)
                  (and (cl:= s1 0)
                       (progn  (sleep 0.1)
                         (cl:= (since t0) 1))))))))

```

**Comment by g000001** [comment]
Thank you for your reporting! 
I've taken your suggestion code. 
fixed: 2506c0717ba5564695af5bd216d6d88236b3b6cd
