### ISSUE TITLE
Lispworks get-time-of-day hack needs fising for 32bit

### ISSUE THREAD

**Issue by Yehouda** [g000001/arc-compat#7]
https://github.com/g000001/arc-compat/blob/b96c15c6c6b5dc459ac5109c74f683ac76a1934d/ac.lisp#L452

This declaration works on 64bit, but on 32bit. On 32bit it is **(unsigned-byte 32)**, so the declaration needs to be:

```
(declare (cl:type (simple-array #+lispworks-64bit (unsigned-byte 64)
                                    #+lispworks-32bit (unsigned-byte 32)
                                    (2)) tv))
```

**Comment by g000001** [comment]
Thank you for your reporting! 
fixed in https://github.com/g000001/arc-compat/commit/0e7f581f286de8fbf9f2f05a7a11efc64b6305d5
